version: '2.1'
services:
  app:
    build: .
    image: app
    ports:
      - '8080:5000'
    volumes:
      - .:/app
  time_delete:
    build:
      context: "../service_time_delete"
    image: time_delete
    volumes:
      - .:/app
