version: '2.1'
services:
  app:
    image: send
    environment: 
      ALLOWED_HOSTS: send,localhost
      DATABASE_URL: sqlite:////database/db.sqlite3
    ports:
      - '8080:5000'
    volumes:
      - database:/database/
  app:
    image: send
    environment: 
      ALLOWED_HOSTS: send,localhost
      DATABASE_URL: sqlite:////database/db.sqlite3
    # ports:
    #   - '4005:4005'
    volumes:
      - database:/database/
volumes:
  database: {}
